name: Release

on:
  release:
    types: [published, prereleased]

permissions:
  contents: write

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4

      - name: Get version
        id: version
        uses: home-assistant/actions/helpers/version@d56d093b9ab8d2105bc0cb6ee9bcc0ef4ec8b96d  # master 2026-03-18

      - name: Set version number
        run: |
          python3 ${{ github.workspace }}/manage/update_manifest.py --version ${{ steps.version.outputs.version }}

      - name: Create zip
        run: |
          cd custom_components/karlstadsenergi
          zip karlstadsenergi.zip -r ./

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@4d54e59003db74f7345a85a1bdb51f76e49b16a4  # v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./custom_components/karlstadsenergi/karlstadsenergi.zip
          asset_name: karlstadsenergi.zip
          tag: ${{ github.ref_name }}
          overwrite: true
